# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      # Configure the builder `pkg_name|builder_name`
      locor:
        # Only run this builder on the specified input.
        generate_for:
          - lib/src/l10n/app_localizations.dart
          - lib/src/l10n/strings.yaml